language: php

php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - cd Tests

script:
  - ./phplint.sh
  - phpunit --configuration Unit.xml

notifications:
  irc:
    channels:
      - "chat.freenode.net##add"
    on_success: change
    on_failure: always